In [3]:
import pandas as pd

In [4]:
indiana_projections_df = pd.read_csv("../chest-x-ray-data/indiana_projections.csv")

In [5]:
indiana_projections_df

       uid                   filename projection
0        1     1_IM-0001-4001.dcm.png    Frontal
1        1     1_IM-0001-3001.dcm.png    Lateral
2        2     2_IM-0652-1001.dcm.png    Frontal
3        2     2_IM-0652-2001.dcm.png    Lateral
4        3     3_IM-1384-1001.dcm.png    Frontal
...    ...                        ...        ...
7461  3997  3997_IM-2048-1002.dcm.png    Lateral
7462  3998  3998_IM-2048-1001.dcm.png    Frontal
7463  3998  3998_IM-2048-1002.dcm.png    Lateral
7464  3999  3999_IM-2049-1001.dcm.png    Frontal
7465  3999  3999_IM-2049-2001.dcm.png    Lateral

[7466 rows x 3 columns]

We only need the frontal images so removing the other images i.e. Lateral Ones

In [ ]:
indiana_projections_df = indiana_projections_df[indiana_projections_df['projection']!='Lateral']

In [8]:
indiana_projections_df

       uid                   filename projection
0        1     1_IM-0001-4001.dcm.png    Frontal
2        2     2_IM-0652-1001.dcm.png    Frontal
4        3     3_IM-1384-1001.dcm.png    Frontal
6        4     4_IM-2050-1001.dcm.png    Frontal
8        5  5_IM-2117-1003002.dcm.png    Frontal
...    ...                        ...        ...
7456  3995  3995_IM-2046-1001.dcm.png    Frontal
7458  3996  3996_IM-2047-1001.dcm.png    Frontal
7460  3997  3997_IM-2048-1001.dcm.png    Frontal
7462  3998  3998_IM-2048-1001.dcm.png    Frontal
7464  3999  3999_IM-2049-1001.dcm.png    Frontal

[3818 rows x 3 columns]

In [12]:
image_file_names = set(indiana_projections_df['filename'])
image_file_names

{'96_IM-2450-2002.dcm.png',
 '1053_IM-0040-1001.dcm.png',
 '2583_IM-1081-1001.dcm.png',
 '2645_IM-1131-2001.dcm.png',
 '481_IM-2105-1001.dcm.png',
 '3300_IM-1578-1001.dcm.png',
 '466_IM-2094-2002.dcm.png',
 '992_IM-2477-0001-0002.dcm.png',
 '3998_IM-2048-1001.dcm.png',
 '1406_IM-0259-1001.dcm.png',
 '1072_IM-0052-1001-0002.dcm.png',
 '5_IM-2117-1003002.dcm.png',
 '3968_IM-2029-3001.dcm.png',
 '1635_IM-0415-1001.dcm.png',
 '2097_IM-0727-1001-0001.dcm.png',
 '1646_IM-0423-1001.dcm.png',
 '2041_IM-0685-3001.dcm.png',
 '3041_IM-1415-1001.dcm.png',
 '2518_IM-1036-1001.dcm.png',
 '2637_IM-1122-4004.dcm.png',
 '1563_IM-0368-1001.dcm.png',
 '2845_IM-1254-1001.dcm.png',
 '3504_IM-1707-1001.dcm.png',
 '2819_IM-1243-1001.dcm.png',
 '225_IM-0844-1001.dcm.png',
 '3625_IM-1794-1001.dcm.png',
 '2259_IM-0850-2001.dcm.png',
 '2996_IM-1381-1001.dcm.png',
 '3130_IM-1472-1001.dcm.png',
 '2489_IM-1016-1001.dcm.png',
 '604_IM-2193-1001.dcm.png',
 '2858_IM-1265-3001.dcm.png',
 '993_IM-2478-1001.dcm.png',
 '271_IM-1176-1001.dcm.png',
 '1614_IM-0397-1001.dcm.png',
 '1707_IM-0466-1001.dcm.png',
 '2074_IM-0708-1001.dcm.png',
 '1163_IM-0108-1001.dcm.png',
 '2431_IM-0973-1001.dcm.png',
 '2691_IM-1163-4004.dcm.png',
 '3427_IM-1657-1001.dcm.png',
 '1112_IM-0078-1001.dcm.png',
 '2263_IM-0853-1001.dcm.png',
 '2801_IM-1233-3003.dcm.png',
 '2560_IM-1064-1001.dcm.png',
 '1381_IM-0245-1001.dcm.png',
 '723_IM-2283-1001.dcm.png',
 '3001_IM-1387-3001.dcm.png',
 '3503_IM-1707-3001.dcm.png',
 '1214_IM-0144-1001.dcm.png',
 '1993_IM-0650-1001.dcm.png',
 '3509_IM-1711-0001-0001.dcm.png',
 '3595_IM-1773-0001-0001.dcm.png',
 '2310_IM-0885-1001.dcm.png',
 '2636_IM-1121-1001.dcm.png',
 '377_IM-1889-1001.dcm.png',
 '1915_IM-0595-1001.dcm.png',
 '3432_IM-1661-1001.dcm.png',
 '2139_IM-0760-1001.dcm.png',
 '2897_IM-1299-1001.dcm.png',
 '170_IM-0461-0001-0003.dcm.png',
 '3536_IM-1729-4004.dcm.png',
 '878_IM-2392-1001.dcm.png',
 '302_IM-1394-1001.dcm.png',
 '1464_IM-0301-1001.dcm.png',
 '59_IM-2184-1001.dcm.png',
 '1897_IM-0581-1001.dcm.png',
 '3024_IM-1399-1001.dcm.png',
 '1937_IM-0607-1001.dcm.png',
 '3363_IM-1616-1001.dcm.png',
 '3704_IM-1851-1001.dcm.png',
 '3159_IM-1487-1001-0001.dcm.png',
 '1591_IM-0384-13013.dcm.png',
 '2762_IM-1208-1001.dcm.png',
 '2936_IM-1338-1002001.dcm.png',
 '1557_IM-0364-4004.dcm.png',
 '1997_IM-0651-1001.dcm.png',
 '2384_IM-0942-1001.dcm.png',
 '1029_IM-0022-1001.dcm.png',
 '1561_IM-0367-1001.dcm.png',
 '3410_IM-1648-1001.dcm.png',
 '380_IM-1911-2001.dcm.png',
 '385_IM-1948-1001.dcm.png',
 '721_IM-2282-1001.dcm.png',
 '1257_IM-0174-1001.dcm.png',
 '3797_IM-1910-0001-0002.dcm.png',
 '2179_IM-0791-1001.dcm.png',
 '257_IM-1072-1001.dcm.png',
 '949_IM-2444-1001.dcm.png',
 '1501_IM-0327-1001.dcm.png',
 '3227_IM-1525-1001.dcm.png',
 '3665_IM-1823-1001.dcm.png',
 '1022_IM-0017-2001.dcm.png',
 '1509_IM-0331-1001.dcm.png',
 '1831_IM-0538-2001.dcm.png',
 '393_IM-2002-1001.dcm.png',
 '3229_IM-1526-1001.dcm.png',
 '3063_IM-1428-1001.dcm.png',
 '632_IM-2213-1001.dcm.png',
 '3064_IM-1428-1001.dcm.png',
 '1867_IM-0560-4004.dcm.png',
 '1940_IM-0610-2002.dcm.png',
 '1545_IM-0355-2002.dcm.png',
 '243_IM-0971-2001.dcm.png',
 '73_IM-2289-1001.dcm.png',
 '2078_IM-0710-1001.dcm.png',
 '2451_IM-0987-1001.dcm.png',
 '2885_IM-1287-2001.dcm.png',
 '3315_IM-1586-1001.dcm.png',
 '3046_IM-1418-1001.dcm.png',
 '3821_IM-1929-1001.dcm.png',
 '580_IM-2177-2002.dcm.png',
 '3171_IM-1494-1001.dcm.png',
 '3802_IM-1912-1001-0002.dcm.png',
 '3965_IM-2028-3001.dcm.png',
 '2554_IM-1059-1001.dcm.png',
 '3242_IM-1534-1001.dcm.png',
 '3434_IM-1662-1001.dcm.png',
 '2902_IM-1306-4001.dcm.png',
 '3993_IM-2044-1001.dcm.png',
 '2824_IM-1245-13001.dcm.png',
 '1114_IM-0079-1001.dcm.png',
 '3510_IM-1713-4004.dcm.png',
 '120_IM-0133-1001.dcm.png',
 '1975_IM-0634-3001.dcm.png',
 '2225_IM-0829-3001.dcm.png',
 '3539_IM-1731-1001.dcm.png',
 '357_IM-1753-1001.dcm.png',
 '2485_IM-1013-1001.dcm.png',
 '2778_IM-1218-1001.dcm.png',
 '2258_IM-0849-1001.dcm.png',
 '3108_IM-1457-1001.dcm.png',
 '2036_IM-0680-4001.dcm.png',
 '2690_IM-1162-1003002.dcm.png',
 '1797_IM-0517-1001.dcm.png',
 '2308_IM-0883-3001.dcm.png',
 '3971_IM-2031-3001.dcm.png',
 '2005_IM-0656-1001.dcm.png',
 '1626_IM-0407-1001.dcm.png',
 '3727_IM-1863-1001.dcm.png',
 '1537_IM-0348-1001.dcm.png',
 '1976_IM-0635-1001-0001.dcm.png',
 '3022_IM-1397-1001.dcm.png',
 '3033_IM-1408-1001.dcm.png',
 '471_IM-2099-2002.dcm.png',
 '484_IM-2108-1001.dcm.png',
 '3592_IM-1771-1001.dcm.png',
 '3670_IM-1826-1001.dcm.png',
 '507_IM-2125-1001.dcm.png',
 '2165_IM-0781-0001-0001.dcm.png',
 '3987_IM-2041-1001.dcm.png',
 '3359_IM-1612-4001.dcm.png',
 '313_IM-1472-1001.dcm.png',
 '2684_IM-1157-1001.dcm.png',
 '1419_IM-0267-1001.dcm.png',
 '436_IM-2076-1001-0002.dcm.png',
 '553_IM-2155-2001.dcm.png',
 '1950_IM-0618-1001.dcm.png',
 '999_IM-2480-1001.dcm.png',
 '3549_IM-1739-1001-0002.dcm.png',
 '3995_IM-2046-1001.dcm.png',
 '3094_IM-1447-2001.dcm.png',
 '1394_IM-0251-1001.dcm.png',
 '1283_IM-0188-1001.dcm.png',
 '1672_IM-0443-4001.dcm.png',
 '1279_IM-0185-1001.dcm.png',
 '2484_IM-1012-1001.dcm.png',
 '2660_IM-1142-1001.dcm.png',
 '3267_IM-1551-1001.dcm.png',
 '2847_IM-1256-1001.dcm.png',
 '1040_IM-0032-4004.dcm.png',
 '3309_IM-1583-1001.dcm.png',
 '2068_IM-0701-1001.dcm.png',
 '2046_IM-0688-1001.dcm.png',
 '2328_IM-0898-1001.dcm.png',
 '2034_IM-0679-2001.dcm.png',
 '1205_IM-0138-1001.dcm.png',
 '1272_IM-0183-1001.dcm.png',
 '3511_IM-1714-1001.dcm.png',
 '1694_IM-0455-1001.dcm.png',
 '793_IM-2330-1001.dcm.png',
 '3468_IM-1684-0001-0004.dcm.png',
 '867_IM-2387-1001.dcm.png',
 '3109_IM-1458-1001.dcm.png',
 '3450_IM-1673-1001.dcm.png',
 '3956_IM-2021-1001.dcm.png',
 '316_IM-1487-1001.dcm.png',
 '1804_IM-0522-82050001.dcm.png',
 '1573_IM-0374-1001.dcm.png',
 '772_IM-2317-0001-0002.dcm.png',
 '2273_IM-0861-1001.dcm.png',
 '326_IM-1546-2002.dcm.png',
 '341_IM-1648-1001.dcm.png',
 '394_IM-2010-1001.dcm.png',
 '862_IM-2383-1001.dcm.png',
 '438_IM-2078-1001.dcm.png',
 '2188_IM-0798-2002.dcm.png',
 '2065_IM-0701-1001.dcm.png',
 '295_IM-1348-1001.dcm.png',
 '1680_IM-0448-1001.dcm.png',
 '1082_IM-0058-1001.dcm.png',
 '2224_IM-0828-1001.dcm.png',
 '2626_IM-1113-2001.dcm.png',
 '3601_IM-1777-2002.dcm.png',
 '2355_IM-0919-1001.dcm.png',
 '2352_IM-0918-1002.dcm.png',
 '3429_IM-1657-1001.dcm.png',
 '3901_IM-1980-1001.dcm.png',
 '1287_IM-0188-1001.dcm.png',
 '2966_IM-1359-1001.dcm.png',
 '2170_IM-0786-1001.dcm.png',
 '3455_IM-1677-1001.dcm.png',
 '11_IM-0067-1001.dcm.png',
 '2694_IM-1165-1001.dcm.png',
 '751_IM-2305-1001.dcm.png',
 '1520_IM-0336-1002001.dcm.png',
 '3782_IM-1898-1001.dcm.png',
 '1315_IM-0204-1001.dcm.png',
 '1551_IM-0359-1001.dcm.png',
 '82_IM-2350-3001.dcm.png',
 '1305_IM-0199-1001.dcm.png',
 '227_IM-0859-12012.dcm.png',
 '841_IM-2365-1001.dcm.png',
 '3716_IM-1856-3001.dcm.png',
 '1882_IM-0571-1001.dcm.png',
 '253_IM-1045-1001.dcm.png',
 '2792_IM-1226-1001.dcm.png',
 '1089_IM-0061-1001.dcm.png',
 '483_IM-2107-1001.dcm.png',
 '1348_IM-0226-4004-0002.dcm.png',
 '3568_IM-1753-1001.dcm.png',
 '2432_IM-0974-1001.dcm.png',
 '3355_IM-1609-1001.dcm.png',
 '2082_IM-0714-4004.dcm.png',
 '756_IM-2307-1001.dcm.png',
 '986_IM-2473-2002.dcm.png',
 '255_IM-1058-1001.dcm.png',
 '730_IM-2290-1001.dcm.png',
 '185_IM-0551-1001.dcm.png',
 '3040_IM-1414-12012.dcm.png',
 '102_IM-0016-1001.dcm.png',
 '3723_IM-1860-1001.dcm.png',
 '3392_IM-1637-1001.dcm.png',
 '1303_IM-0199-2001-0001.dcm.png',
 '2300_IM-0881-1001.dcm.png',
 '2522_IM-1040-1001.dcm.png',
 '3948_IM-2017-1001.dcm.png',
 '1130_IM-0087-1001.dcm.png',
 '2280_IM-0867-1001-0001.dcm.png',
 '1731_IM-0481-2001.dcm.png',
 '2315_IM-0889-1003.dcm.png',
 '2714_IM-1180-1001.dcm.png',
 '683_IM-2254-1001.dcm.png',
 '2119_IM-0746-1001.dcm.png',
 '1196_IM-0131-1001.dcm.png',
 '448_IM-2080-1001.dcm.png',
 '2378_IM-0938-1001.dcm.png',
 '3330_IM-1594-1001.dcm.png',
 '409_IM-2055-2001.dcm.png',
 '1714_IM-0472-1001.dcm.png',
 '784_IM-2325-1001-0002.dcm.png',
 '397_IM-2030-1001.dcm.png',
 '1754_IM-0494-1001.dcm.png',
 '3340_IM-1601-1001.dcm.png',
 '256_IM-1064-1001.dcm.png',
 '667_IM-2241-1001.dcm.png',
 '425_IM-2068-1001.dcm.png',
 '3666_IM-1824-1001.dcm.png',
 '1006_IM-0007-1001.dcm.png',
 '719_IM-2280-1001.dcm.png',
 '45_IM-2081-1001.dcm.png',
 '1880_IM-0569-1001.dcm.png',
 '3657_IM-1818-1001.dcm.png',
 '3958_IM-2022-1001.dcm.png',
 '2133_IM-0756-1001.dcm.png',
 '2066_IM-0701-1001.dcm.png',
 '938_IM-2434-1001.dcm.png',
 '122_IM-0147-0001-0001.dcm.png',
 '416_IM-2059-1001.dcm.png',
 '1708_IM-0466-1001.dcm.png',
 '314_IM-1477-1001.dcm.png',
 '1342_IM-0221-1001.dcm.png',
 '1491_IM-0317-1001.dcm.png',
 '3185_IM-1503-1001.dcm.png',
 '578_IM-2176-1001.dcm.png',
 '342_IM-1655-0001-0001.dcm.png',
 '3343_IM-1603-1001.dcm.png',
 '3390_IM-1636-3001.dcm.png',
 '3088_IM-1444-1001.dcm.png',
 '1534_IM-0345-4004.dcm.png',
 '136_IM-0233-1001.dcm.png',
 '2559_IM-1063-1001.dcm.png',
 '2903_IM-1307-4004.dcm.png',
 '663_IM-2239-1001.dcm.png',
 '392_IM-1993-1001.dcm.png',
 '3619_IM-1791-1001.dcm.png',
 '3026_IM-1401-1001.dcm.png',
 '3585_IM-1763-1001.dcm.png',
 '1090_IM-0062-1001.dcm.png',
 '1930_IM-0602-1001-0002.dcm.png',
 '1909_IM-0590-1001.dcm.png',
 '3350_IM-1607-0001-0001.dcm.png',
 '3972_IM-2032-1001.dcm.png',
 '2054_IM-0692-0001-0002.dcm.png',
 '2954_IM-1352-2001.dcm.png',
 '3403_IM-1647-1001.dcm.png',
 '2989_IM-1376-1001.dcm.png',
 '646_IM-2225-1001.dcm.png',
 '1137_IM-0093-4004.dcm.png',
 '2374_IM-0935-84550001.dcm.png',
 '1712_IM-0470-3001.dcm.png',
 '960_IM-2451-4004.dcm.png',
 '134_IM-0219-1001.dcm.png',
 '983_IM-2471-1001.dcm.png',
 '1246_IM-0167-1001.dcm.png',
 '1411_IM-0261-0001-0001.dcm.png',
 '2659_IM-1140-1001.dcm.png',
 '3494_IM-1699-1001.dcm.png',
 '2779_IM-1218-1001.dcm.png',
 '1965_IM-0629-1001.dcm.png',
 '2377_IM-0937-1001.dcm.png',
 '1597_IM-0388-1001.dcm.png',
 '3662_IM-1821-1001.dcm.png',
 '3222_IM-1522-1001.dcm.png',
 '63_IM-2210-0001-0001.dcm.png',
 '1326_IM-0210-0001-0002.dcm.png',
 '1820_IM-0532-1001.dcm.png',
 '3372_IM-1623-1001.dcm.png',
 '3879_IM-1968-1001.dcm.png',
 '3269_IM-1552-1001.dcm.png',
 '1722_IM-0476-1001.dcm.png',
 '1308_IM-0201-1001.dcm.png',
 '2113_IM-0742-1002.dcm.png',
 '1120_IM-0080-1001.dcm.png',
 '1980_IM-0637-1001.dcm.png',
 '2187_IM-0797-1001.dcm.png',
 '977_IM-2465-1001.dcm.png',
 '1769_IM-0503-1001.dcm.png',
 '1352_IM-0229-1001.dcm.png',
 '3015_IM-1392-1001.dcm.png',
 '1384_IM-0246-1001.dcm.png',
 '2243_IM-0840-4001.dcm.png',
 '2254_IM-0846-1001.dcm.png',
 '2147_IM-0767-1001.dcm.png',
 '1554_IM-0361-1001.dcm.png',
 '2542_IM-1053-1001.dcm.png',
 '1656_IM-0431-1001.dcm.png',
 '200_IM-0653-1001.dcm.png',
 '1487_IM-0314-1001.dcm.png',
 '205_IM-0689-2002.dcm.png',
 '2591_IM-1083-1001.dcm.png',
 '2827_IM-1246-1001.dcm.png',
 '3243_IM-1535-0001-0001.dcm.png',
 '3849_IM-1947-1001.dcm.png',
 '1719_IM-0474-1001.dcm.png',
 '338_IM-1628-1001.dcm.png',
 '2173_IM-0786-1001.dcm.png',
 '1574_IM-0374-1001.dcm.png',
 '1195_IM-0131-1001.dcm.png',
 '3391_IM-1637-2001.dcm.png',
 '863_IM-2383-3001.dcm.png',
 '2850_IM-1259-2002.dcm.png',
 '374_IM-1868-1001.dcm.png',
 '2810_IM-1238-1001.dcm.png',
 '3157_IM-1487-1001.dcm.png',
 '565_IM-2166-1001.dcm.png',
 '2402_IM-0951-1001.dcm.png',
 '3789_IM-1902-1001.dcm.png',
 '3780_IM-1896-3003.dcm.png',
 '2566_IM-1068-1001.dcm.png',
 '2908_IM-1312-4004.dcm.png',
 '3028_IM-1403-1001.dcm.png',
 '1824_IM-0535-1001.dcm.png',
 '239_IM-0944-1001.dcm.png',
 '1485_IM-0313-1001.dcm.png',
 '1808_IM-0524-1001.dcm.png',
 '1151_IM-0102-1001.dcm.png',
 '192_IM-0598-1001.dcm.png',
 '53_IM-2138-1001.dcm.png',
 '1078_IM-0055-1001.dcm.png',
 '2269_IM-0858-1001.dcm.png',
 '55_IM-2154-1001.dcm.png',
 '3258_IM-1544-1001.dcm.png',
 '2874_IM-1280-1001.dcm.png',
 '1382_IM-0245-1001.dcm.png',
 '595_IM-2187-1001.dcm.png',
 '248_IM-1008-85149002.dcm.png',
 '1301_IM-0198-1001.dcm.png',
 '1780_IM-0509-1001.dcm.png',
 '473_IM-2101-1001.dcm.png',
 '1161_IM-0107-1001.dcm.png',
 '2805_IM-1235-1001.dcm.png',
 '1193_IM-0129-1001.dcm.png',
 '19_IM-0583-1001.dcm.png',
 '3148_IM-1480-1001.dcm.png',
 '3460_IM-1681-1001.dcm.png',
 '3530_IM-1726-1001.dcm.png',
 '2906_IM-1310-1001.dcm.png',
 '3709_IM-1852-1001.dcm.png',
 '3983_IM-2039-1001.dcm.png',
 '857_IM-2378-1001.dcm.png',
 '2786_IM-1221-1001.dcm.png',
 '540_IM-2146-4004.dcm.png',
 '3874_IM-1966-1001.dcm.png',
 '1488_IM-0315-1001.dcm.png',
 '2401_IM-0950-1001.dcm.png',
 '2975_IM-1364-1001.dcm.png',
 '3673_IM-1828-1001.dcm.png',
 '2676_IM-1151-1001.dcm.png',
 '3796_IM-1909-1001.dcm.png',
 '2375_IM-0936-1001.dcm.png',
 '3009_IM-1389-1001.dcm.png',
 '2806_IM-1236-1001.dcm.png',
 '490_IM-2110-1001.dcm.png',
 '3058_IM-1425-12012.dcm.png',
 '3469_IM-1685-1001.dcm.png',
 '2264_IM-0854-1001.dcm.png',
 '657_IM-2233-0001-0001.dcm.png',
 '1473_IM-0306-1001.dcm.png',
 '411_IM-2056-1001.dcm.png',
 '907_IM-2412-82526002.dcm.png',
 '2372_IM-0933-0001-0001.dcm.png',
 '3406_IM-1647-1001.dcm.png',
 '3593_IM-1772-1001.dcm.png',
 '2696_IM-1166-1001.dcm.png',
 '727_IM-2287-1001.dcm.png',
 '3832_IM-1935-1002001.dcm.png',
 '2702_IM-1170-1001.dcm.png',
 '3724_IM-1860-2001.dcm.png',
 '278_IM-1218-1001.dcm.png',
 '1056_IM-0040-1002.dcm.png',
 '2843_IM-1254-1001-0002.dcm.png',
 '1465_IM-0302-1001.dcm.png',
 '3387_IM-1633-1001.dcm.png',
 '3393_IM-1637-1001.dcm.png',
 '3753_IM-1877-1001.dcm.png',
 '3284_IM-1565-20001.dcm.png',
 '3877_IM-1967-1001.dcm.png',
 '1615_IM-0398-4004.dcm.png',
 '32_IM-1511-1001.dcm.png',
 '2231_IM-0831-2001.dcm.png',
 '359_IM-1768-1001.dcm.png',
 '315_IM-1481-1001.dcm.png',
 '1070_IM-0050-1001.dcm.png',
 '68_IM-2251-1001.dcm.png',
 '3191_IM-1505-1001.dcm.png',
 '266_IM-1141-4004.dcm.png',
 '1433_IM-0278-1001.dcm.png',
 '1254_IM-0172-1001.dcm.png',
 '1173_IM-0118-5001.dcm.png',
 '3542_IM-1734-1001.dcm.png',
 '3588_IM-1766-1001.dcm.png',
 '2153_IM-0773-1001.dcm.png',
 '1032_IM-0026-1001-0002.dcm.png',
 '3842_IM-1943-1001.dcm.png',
 '388_IM-1968-1001.dcm.png',
 '3815_IM-1924-1001.dcm.png',
 '2234_IM-0833-1001.dcm.png',
 '51_IM-2125-1001.dcm.png',
 '1459_IM-0297-1001.dcm.png',
 '1228_IM-0151-1001.dcm.png',
 '832_IM-2359-1001.dcm.png',
 '1383_IM-0245-1001.dcm.png',
 '1460_IM-0298-1001.dcm.png',
 '1710_IM-0469-1001.dcm.png',
 '3025_IM-1400-1001.dcm.png',
 '3199_IM-1510-1001.dcm.png',
 '3400_IM-1644-1001.dcm.png',
 '2303_IM-0882-1001.dcm.png',
 '2266_IM-0855-1001.dcm.png',
 '1412_IM-0262-1001.dcm.png',
 '875_IM-2392-1001.dcm.png',
 '734_IM-2293-0001-0002.dcm.png',
 '2930_IM-1333-1002001.dcm.png',
 '2573_IM-1074-1001.dcm.png',
 '1709_IM-0467-1001.dcm.png',
 '2770_IM-1213-1001.dcm.png',
 '1189_IM-0128-1001.dcm.png',
 '282_IM-1243-1001.dcm.png',
 '653_IM-2230-1001.dcm.png',
 '1133_IM-0090-1001.dcm.png',
 '3609_IM-1782-2001.dcm.png',
 '1734_IM-0484-1001.dcm.png',
 '2704_IM-1171-1001.dcm.png',
 '3720_IM-1859-1001.dcm.png',
 '1459_IM-0297-3001.dcm.png',
 '413_IM-2056-1001.dcm.png',
 '762_IM-2310-1001.dcm.png',
 '2169_IM-0785-0001-0002.dcm.png',
 '815_IM-2346-1001.dcm.png',
 '2958_IM-1354-1001.dcm.png',
 '152_IM-0335-2001.dcm.png',
 '64_IM-2218-4004.dcm.png',
 '347_IM-1686-1001.dcm.png',
 '1389_IM-0247-1001.dcm.png',
 '2568_IM-1070-1001.dcm.png',
 '3964_IM-2028-1001.dcm.png',
 '1931_IM-0602-1001.dcm.png',
 '1104_IM-0071-1001.dcm.png',
 '2985_IM-1373-1001.dcm.png',
 '3097_IM-1449-1001.dcm.png',
 '2323_IM-0895-12012.dcm.png',
 '1367_IM-0237-1001.dcm.png',
 '2239_IM-0836-1001.dcm.png',
 '1259_IM-0175-1001.dcm.png',
 '3230_IM-1527-2001.dcm.png',
 '3444_IM-1667-1001.dcm.png',
 '1416_IM-0265-1001.dcm.png',
 '2087_IM-0718-3001.dcm.png',
 '2398_IM-0947-4004.dcm.png',
 '1891_IM-0580-1001.dcm.png',
 '797_IM-2332-1001.dcm.png',
 '1145_IM-0097-2002.dcm.png',
 '2299_IM-0878-1001.dcm.png',
 '1630_IM-0411-1001.dcm.png',
 '3863_IM-1957-1001.dcm.png',
 '3321_IM-1588-1001.dcm.png',
 '2128_IM-0752-1001.dcm.png',
 '3598_IM-1775-1001.dcm.png',
 '615_IM-2200-1001.dcm.png',
 '2705_IM-1171-1001.dcm.png',
 '188_IM-0569-1001.dcm.png',
 '948_IM-2443-1001.dcm.png',
 '1478_IM-0310-0001-0003.dcm.png',
 '1249_IM-0169-1001.dcm.png',
 '456_IM-2087-1001.dcm.png',
 '790_IM-2329-1001.dcm.png',
 '3807_IM-1917-1001.dcm.png',
 '3607_IM-1781-1001.dcm.png',
 '664_IM-2240-1001.dcm.png',
 '1401_IM-0256-1001.dcm.png',
 '2407_IM-0954-1001.dcm.png',
 '1349_IM-0227-1001.dcm.png',
 '77_IM-2315-1001-0002.dcm.png',
 '399_IM-2043-1001.dcm.png',
 '714_IM-2276-3001.dcm.png',
 '2216_IM-0821-85075001.dcm.png',
 '2475_IM-1004-1001.dcm.png',
 '1476_IM-0308-1001.dcm.png',
 '240_IM-0950-1001.dcm.png',
 '2012_IM-0662-3001.dcm.png',
 '2537_IM-1049-1001.dcm.png',
 '2744_IM-1197-1001.dcm.png',
 '2925_IM-1327-1001.dcm.png',
 '3940_IM-2011-1001.dcm.png',
 '3677_IM-1830-2001.dcm.png',
 '2080_IM-0712-2002.dcm.png',
 '378_IM-1895-4001.dcm.png',
 '1324_IM-0209-1001.dcm.png',
 '2553_IM-1059-1001.dcm.png',
 '3522_IM-1720-1001.dcm.png',
 '609_IM-2197-1001.dcm.png',
 '478_IM-2101-1001-0002.dcm.png',
 '3774_IM-1892-1001.dcm.png',
 '1954_IM-0622-1001.dcm.png',
 '2633_IM-1120-2002.dcm.png',
 '285_IM-1258-4004.dcm.png',
 '818_IM-2349-1001.dcm.png',
 '1505_IM-0330-1001.dcm.png',
 '67_IM-2243-8001.dcm.png',
 '2822_IM-1244-2002.dcm.png',
 '2157_IM-0775-1001.dcm.png',
 '3211_IM-1517-1001-0002.dcm.png',
 '3547_IM-1739-1001.dcm.png',
 '933_IM-2431-1001.dcm.png',
 '3851_IM-1948-1001.dcm.png',
 '1280_IM-0187-1001.dcm.png',
 '3857_IM-1952-1001.dcm.png',
 '1456_IM-0294-1001.dcm.png',
 '746_IM-2300-3001.dcm.png',
 '78_IM-2322-3001.dcm.png',
 '513_IM-2128-1001.dcm.png',
 '2552_IM-1058-1001.dcm.png',
 '3281_IM-1562-3001.dcm.png',
 '712_IM-2274-0001-0001.dcm.png',
 '3773_IM-1891-1001.dcm.png',
 '3581_IM-1761-1001.dcm.png',
 '3196_IM-1507-1001.dcm.png',
 '849_IM-2371-1001.dcm.png',
 '1639_IM-0418-1001.dcm.png',
 '2198_IM-0808-1001.dcm.png',
 '1147_IM-0099-4004.dcm.png',
 '2712_IM-1179-2001.dcm.png',
 '3545_IM-1737-2002.dcm.png',
 '1322_IM-0208-3003.dcm.png',
 '1220_IM-0148-1001.dcm.png',
 '2957_IM-1354-1003.dcm.png',
 '964_IM-2454-1001.dcm.png',
 '3908_IM-1985-1001.dcm.png',
 '1238_IM-0160-2002.dcm.png',
 '1974_IM-0633-1001.dcm.png',
 '3026_IM-1401-3001.dcm.png',
 '1472_IM-0305-1001.dcm.png',
 '2418_IM-0962-5001.dcm.png',
 '197_IM-0631-1001.dcm.png',
 '2979_IM-1368-1001-0001.dcm.png',
 '3018_IM-1393-1001.dcm.png',
 '3967_IM-2028-1001.dcm.png',
 '982_IM-2470-1001.dcm.png',
 '444_IM-2079-1001.dcm.png',
 '3740_IM-1868-1001.dcm.png',
 '3386_IM-1633-1001.dcm.png',
 '1231_IM-0155-1001.dcm.png',
 '3745_IM-1872-1001.dcm.png',
 '1417_IM-0266-1001.dcm.png',
 '90_IM-2407-1001.dcm.png',
 '635_IM-2215-1001.dcm.png',
 '2852_IM-1261-3001.dcm.png',
 '387_IM-1962-1001.dcm.png',
 '458_IM-2089-1001.dcm.png',
 '2557_IM-1061-4004.dcm.png',
 '3632_IM-1799-2001.dcm.png',
 '1471_IM-0304-2001.dcm.png',
 '2459_IM-0991-1001.dcm.png',
 '3071_IM-1433-1001.dcm.png',
 '773_IM-2318-1001.dcm.png',
 '105_IM-0037-1001.dcm.png',
 '1759_IM-0495-1001.dcm.png',
 '3446_IM-1669-1001.dcm.png',
 '3081_IM-1440-1001.dcm.png',
 '2158_IM-0776-1001.dcm.png',
 '2411_IM-0957-0001-0002.dcm.png',
 '1849_IM-0550-1001.dcm.png',
 '2348_IM-0913-1001.dcm.png',
 '864_IM-2384-1001.dcm.png',
 '210_IM-0730-1001.dcm.png',
 '1846_IM-0549-3001.dcm.png',
 '2624_IM-1111-1001.dcm.png',
 '3975_IM-2035-1001.dcm.png',
 '1637_IM-0416-1001.dcm.png',
 '828_IM-2357-1001.dcm.png',
 '2466_IM-0997-1001.dcm.png',
 '2056_IM-0694-1001-0002.dcm.png',
 '3471_IM-1687-2002.dcm.png',
 '1995_IM-0651-1001.dcm.png',
 '113_IM-0086-3001.dcm.png',
 '1437_IM-0281-3001.dcm.png',
 '3608_IM-1781-1001.dcm.png',
 '825_IM-2355-1001.dcm.png',
 '3760_IM-1883-1001.dcm.png',
 '1521_IM-0337-1001.dcm.png',
 '3381_IM-1628-1001.dcm.png',
 '1461_IM-0299-1001.dcm.png',
 '2177_IM-0789-4001.dcm.png',
 '2717_IM-1181-1001-0001.dcm.png',
 '2191_IM-0801-1001.dcm.png',
 '2802_IM-1234-1001.dcm.png',
 '2783_IM-1220-1001.dcm.png',
 '1691_IM-0453-4001.dcm.png',
 '1748_IM-0490-1001.dcm.png',
 '284_IM-1252-5005.dcm.png',
 '1314_IM-0204-1001.dcm.png',
 '3170_IM-1494-1001.dcm.png',
 '470_IM-2099-3001.dcm.png',
 '1881_IM-0570-3001.dcm.png',
 '2826_IM-1246-1001.dcm.png',
 '457_IM-2088-1001-0001.dcm.png',
 '3111_IM-1461-1001.dcm.png',
 '1634_IM-0414-2002.dcm.png',
 '2209_IM-0816-1001.dcm.png',
 '606_IM-2195-1001.dcm.png',
 '3298_IM-1575-1001.dcm.png',
 '2740_IM-1195-1001.dcm.png',

In [32]:
import glob
import os
import shutil

In [33]:
images = glob.glob(r'..\chest-x-ray-data\images\*.png')
destination_folder = r'..\chest-x-ray-data\processed_images'

# create folder if it doesn't exist
os.makedirs(destination_folder, exist_ok=True)

Moving the lateral x-ray images into another folder

In [ ]:

for image in images:
   file_name = os.path.basename(image)
   if file_name not in image_file_names:
      destination_path = os.path.join(destination_folder, file_name)
      shutil.move(image, destination_path)
      print(f"Moved the file {file_name}")

Moved the file 1000_IM-0003-2001.dcm.png
Moved the file 1001_IM-0004-1002.dcm.png
Moved the file 1002_IM-0004-2001.dcm.png
Moved the file 1004_IM-0005-2001.dcm.png
Moved the file 1005_IM-0006-3003.dcm.png
Moved the file 1006_IM-0007-3003.dcm.png
Moved the file 1007_IM-0008-2001.dcm.png
Moved the file 1008_IM-0009-2001.dcm.png
Moved the file 1009_IM-0010-2001.dcm.png
Moved the file 100_IM-0002-2001.dcm.png
Moved the file 1010_IM-0012-2001.dcm.png
Moved the file 1011_IM-0013-1002.dcm.png
Moved the file 1013_IM-0013-2001.dcm.png
Moved the file 1014_IM-0013-2001.dcm.png
Moved the file 1015_IM-0001-2001.dcm.png
Moved the file 1015_IM-0013-2001.dcm.png
Moved the file 1016_IM-0013-2001.dcm.png
Moved the file 1017_IM-0013-1002.dcm.png
Moved the file 1018_IM-0014-6001.dcm.png
Moved the file 1019_IM-0015-2001.dcm.png
Moved the file 101_IM-0011-2001.dcm.png
Moved the file 1020_IM-0017-2001.dcm.png
Moved the file 1021_IM-0017-1001-0002.dcm.png
Moved the file 1022_IM-0017-1001.dcm.png
Moved the file 1023_IM-0018-2001.dcm.png
Moved the file 1025_IM-0020-3001.dcm.png
Moved the file 1027_IM-0021-2001.dcm.png
Moved the file 1028_IM-0022-2001.dcm.png
Moved the file 102_IM-0016-2001.dcm.png
Moved the file 1030_IM-0024-2001.dcm.png
Moved the file 1032_IM-0026-1001-0001.dcm.png
Moved the file 1033_IM-0027-2001.dcm.png
Moved the file 1034_IM-0028-1002.dcm.png
Moved the file 1035_IM-0028-2001.dcm.png
Moved the file 1037_IM-0029-2001.dcm.png
Moved the file 1038_IM-0029-2001.dcm.png
Moved the file 103_IM-0023-2001.dcm.png
Moved the file 1040_IM-0032-2001.dcm.png
Moved the file 1041_IM-0033-2001.dcm.png
Moved the file 1042_IM-0034-3001.dcm.png
Moved the file 1043_IM-0035-0001-0001.dcm.png
Moved the file 1044_IM-0036-2001.dcm.png
Moved the file 1045_IM-0036-2001.dcm.png
Moved the file 1046_IM-0036-2001.dcm.png
Moved the file 1047_IM-0036-1001.dcm.png
Moved the file 1048_IM-0036-2001.dcm.png
Moved the file 1049_IM-0036-3001.dcm.png
Moved the file 104_IM-0031-0001-0002.dcm.png
Moved the file 1050_IM-0038-2001.dcm.png
Moved the file 1051_IM-0039-6001.dcm.png
Moved the file 1052_IM-0040-1002.dcm.png
Moved the file 1053_IM-0040-3003.dcm.png
Moved the file 1054_IM-0040-1002.dcm.png
Moved the file 1055_IM-0040-2001.dcm.png
Moved the file 1056_IM-0040-1003.dcm.png
Moved the file 1057_IM-0041-2001.dcm.png
Moved the file 1058_IM-0041-2001.dcm.png
Moved the file 105_IM-0037-2001.dcm.png
Moved the file 1060_IM-0042-2001.dcm.png
Moved the file 1061_IM-0043-2001.dcm.png
Moved the file 1063_IM-0044-84654002.dcm.png
Moved the file 1065_IM-0046-2001.dcm.png
Moved the file 1066_IM-0047-2001.dcm.png
Moved the file 1067_IM-0048-2001.dcm.png
Moved the file 106_IM-0042-2001.dcm.png
Moved the file 1070_IM-0050-2001.dcm.png
Moved the file 1071_IM-0051-2001.dcm.png
Moved the file 1072_IM-0052-1001-0001.dcm.png
Moved the file 1073_IM-0053-2001.dcm.png
Moved the file 1074_IM-0054-2001.dcm.png
Moved the file 1075_IM-0054-2001.dcm.png
Moved the file 1076_IM-0054-3001.dcm.png
Moved the file 1077_IM-0054-2001.dcm.png
Moved the file 1078_IM-0055-2001.dcm.png
Moved the file 1079_IM-0056-2001.dcm.png
Moved the file 107_IM-0049-2001.dcm.png
Moved the file 1083_IM-0058-2001.dcm.png
Moved the file 1084_IM-0058-2001.dcm.png
Moved the file 1085_IM-0059-2001.dcm.png
Moved the file 1086_IM-0059-2001.dcm.png
Moved the file 1087_IM-0060-1004003.dcm.png
Moved the file 1088_IM-0061-2001.dcm.png
Moved the file 1089_IM-0061-2001.dcm.png
Moved the file 108_IM-0056-1002.dcm.png
Moved the file 1090_IM-0062-1002.dcm.png
Moved the file 1091_IM-0062-2001.dcm.png
Moved the file 1092_IM-0063-2001.dcm.png
Moved the file 1093_IM-0064-3003.dcm.png
Moved the file 1094_IM-0065-2001.dcm.png
Moved the file 1096_IM-0066-2001.dcm.png
Moved the file 1097_IM-0067-2001.dcm.png
Moved the file 1099_IM-0067-2001.dcm.png
Moved the file 10_IM-0002-1001.dcm.png
Moved the file 1100_IM-0068-2001.dcm.png
Moved the file 1101_IM-0068-2001.dcm.png
Moved the file 1102_IM-0069-2001.dcm.png
Moved the file 1102_IM-0069-3001.dcm.png
Moved the file 1103_IM-0070-2001.dcm.png
Moved the file 1104_IM-0071-3001.dcm.png
Moved the file 1104_IM-0071-4001.dcm.png
Moved the file 1105_IM-0072-1001-0002.dcm.png
Moved the file 1106_IM-0073-2001.dcm.png
Moved the file 1108_IM-0075-2001.dcm.png
Moved the file 1109_IM-0076-2001.dcm.png
Moved the file 110_IM-0067-2001.dcm.png
Moved the file 1110_IM-0076-2001.dcm.png
Moved the file 1111_IM-0077-1001.dcm.png
Moved the file 1112_IM-0078-2001.dcm.png
Moved the file 1113_IM-0078-1002.dcm.png
Moved the file 1114_IM-0079-2001.dcm.png
Moved the file 1116_IM-0079-2001.dcm.png
Moved the file 1117_IM-0079-2001.dcm.png
Moved the file 1118_IM-0079-2001.dcm.png
Moved the file 1119_IM-0080-2001.dcm.png
Moved the file 111_IM-0076-1002.dcm.png
Moved the file 1121_IM-0080-2001.dcm.png
Moved the file 1122_IM-0080-2001.dcm.png
Moved the file 1123_IM-0080-2001.dcm.png
Moved the file 1124_IM-0081-3001.dcm.png
Moved the file 1125_IM-0082-1001.dcm.png
Moved the file 1126_IM-0082-2001.dcm.png
Moved the file 1128_IM-0084-6001.dcm.png
Moved the file 112_IM-0080-1002.dcm.png
Moved the file 1130_IM-0087-3003.dcm.png
Moved the file 1131_IM-0088-0001-0001.dcm.png
Moved the file 1133_IM-0090-1002.dcm.png
Moved the file 1134_IM-0091-2001.dcm.png
Moved the file 1135_IM-0091-2001.dcm.png
Moved the file 1136_IM-0092-2001.dcm.png
Moved the file 1138_IM-0094-2001.dcm.png
Moved the file 1139_IM-0095-2001.dcm.png
Moved the file 113_IM-0086-2001.dcm.png
Moved the file 1140_IM-0096-1002.dcm.png
Moved the file 1141_IM-0096-1002.dcm.png
Moved the file 1142_IM-0096-2001.dcm.png
Moved the file 1143_IM-0096-2001.dcm.png
Moved the file 1144_IM-0097-2001.dcm.png
Moved the file 1145_IM-0097-3003.dcm.png
Moved the file 1146_IM-0098-2001.dcm.png
Moved the file 1148_IM-0100-2001.dcm.png
Moved the file 1149_IM-0101-2001.dcm.png
Moved the file 114_IM-0096-2001.dcm.png
Moved the file 1151_IM-0102-2001.dcm.png
Moved the file 1152_IM-0103-2001.dcm.png
Moved the file 1153_IM-0104-2001.dcm.png
Moved the file 1154_IM-0104-2001.dcm.png
Moved the file 1155_IM-0105-0001-0001.dcm.png
Moved the file 1156_IM-0106-2001.dcm.png
Moved the file 1157_IM-0106-2001.dcm.png
Moved the file 1158_IM-0107-2001.dcm.png
Moved the file 115_IM-0102-2001.dcm.png
Moved the file 1160_IM-0107-1002.dcm.png
Moved the file 1161_IM-0107-2001.dcm.png
Moved the file 1162_IM-0108-2001.dcm.png
Moved the file 1163_IM-0108-2001.dcm.png
Moved the file 1164_IM-0109-0001-0001.dcm.png
Moved the file 1166_IM-0111-2001.dcm.png
Moved the file 1167_IM-0112-2001.dcm.png
Moved the file 1168_IM-0112-1002.dcm.png
Moved the file 116_IM-0107-2001.dcm.png
Moved the file 1170_IM-0115-1001.dcm.png
Moved the file 1170_IM-0115-3001.dcm.png
Moved the file 1171_IM-0116-1002.dcm.png
Moved the file 1173_IM-0118-1001.dcm.png
Moved the file 1174_IM-0118-2001.dcm.png
Moved the file 1175_IM-0119-2001.dcm.png
Moved the file 1176_IM-0119-2001.dcm.png
Moved the file 1177_IM-0120-3001.dcm.png
Moved the file 1178_IM-0121-1002.dcm.png
Moved the file 1179_IM-0122-3003.dcm.png
Moved the file 117_IM-0114-3003.dcm.png
Moved the file 1180_IM-0123-2001.dcm.png
Moved the file 1182_IM-0124-2001.dcm.png
Moved the file 1183_IM-0124-2001.dcm.png
Moved the file 1184_IM-0124-2001.dcm.png
Moved the file 1187_IM-0126-2001.dcm.png
Moved the file 1188_IM-0127-2001.dcm.png
Moved the file 1189_IM-0128-2001.dcm.png
Moved the file 118_IM-0123-2001.dcm.png
Moved the file 1190_IM-0128-1003.dcm.png
Moved the file 1191_IM-0128-2001.dcm.png
Moved the file 1192_IM-0129-2001.dcm.png
Moved the file 1193_IM-0129-2001.dcm.png
Moved the file 1194_IM-0130-14001.dcm.png
Moved the file 1195_IM-0131-2001.dcm.png
Moved the file 1196_IM-0131-2001.dcm.png
Moved the file 1197_IM-0131-1002.dcm.png
Moved the file 1198_IM-0132-2001.dcm.png
Moved the file 1199_IM-0133-1002.dcm.png
Moved the file 11_IM-0067-2001.dcm.png
Moved the file 1200_IM-0134-2001.dcm.png
Moved the file 1202_IM-0136-2001.dcm.png
Moved the file 1203_IM-0137-2001.dcm.png
Moved the file 1204_IM-0138-2001.dcm.png
Moved the file 1205_IM-0138-1002.dcm.png
Moved the file 1206_IM-0139-3003.dcm.png
Moved the file 1207_IM-0140-0001-0001.dcm.png
Moved the file 1208_IM-0141-2001.dcm.png
Moved the file 1209_IM-0142-1002.dcm.png
Moved the file 120_IM-0133-2001.dcm.png
Moved the file 1210_IM-0142-2001.dcm.png
Moved the file 1211_IM-0142-1002.dcm.png
Moved the file 1212_IM-0143-2001.dcm.png
Moved the file 1213_IM-0144-2001.dcm.png
Moved the file 1214_IM-0144-2001.dcm.png
Moved the file 1216_IM-0144-2001.dcm.png
Moved the file 1217_IM-0145-0001-0001.dcm.png
Moved the file 1218_IM-0146-2001.dcm.png
Moved the file 1219_IM-0146-2001.dcm.png
Moved the file 121_IM-0142-2001.dcm.png
Moved the file 1220_IM-0148-2001.dcm.png
Moved the file 1221_IM-0149-0001-0001.dcm.png
Moved the file 1222_IM-0150-2001.dcm.png
Moved the file 1223_IM-0150-2001.dcm.png
Moved the file 1225_IM-0150-2001.dcm.png
Moved the file 1226_IM-0150-1002.dcm.png
Moved the file 1228_IM-0151-2001.dcm.png
Moved the file 1228_IM-0151-3001.dcm.png
Moved the file 1229_IM-0152-2001.dcm.png
Moved the file 122_IM-0147-0001-0002.dcm.png
Moved the file 1230_IM-0154-0001.dcm.png
Moved the file 1231_IM-0155-2001.dcm.png
Moved the file 1232_IM-0156-2001.dcm.png
Moved the file 1232_IM-0156-3001.dcm.png
Moved the file 1233_IM-0157-2001.dcm.png
Moved the file 1234_IM-0157-1001.dcm.png
Moved the file 1235_IM-0158-2001.dcm.png
Moved the file 1236_IM-0158-2001.dcm.png
Moved the file 1237_IM-0159-1002.dcm.png
Moved the file 1239_IM-0160-2001.dcm.png
Moved the file 123_IM-0153-1001.dcm.png
Moved the file 1240_IM-0162-2001.dcm.png
Moved the file 1242_IM-0164-2001.dcm.png
Moved the file 1243_IM-0165-1001.dcm.png
Moved the file 1243_IM-0165-2001.dcm.png
Moved the file 1244_IM-0166-1001.dcm.png
Moved the file 1245_IM-0167-2001.dcm.png
Moved the file 1246_IM-0167-2001.dcm.png
Moved the file 1248_IM-0168-2001.dcm.png
Moved the file 1249_IM-0169-2001.dcm.png
Moved the file 124_IM-0161-1001.dcm.png
Moved the file 1250_IM-0169-2001.dcm.png
Moved the file 1252_IM-0170-1002.dcm.png
Moved the file 1253_IM-0171-0001-0001.dcm.png
Moved the file 1254_IM-0172-2001.dcm.png
Moved the file 1255_IM-0172-1001-0002.dcm.png
Moved the file 1256_IM-0173-2001.dcm.png
Moved the file 1257_IM-0174-2001.dcm.png
Moved the file 1259_IM-0175-2001.dcm.png
Moved the file 125_IM-0169-2001.dcm.png
Moved the file 1260_IM-0176-2001.dcm.png
Moved the file 1260_IM-0176-3001.dcm.png
Moved the file 1261_IM-0177-2001.dcm.png
Moved the file 1262_IM-0178-1001.dcm.png
Moved the file 1262_IM-0178-2001.dcm.png
Moved the file 1263_IM-0179-3001.dcm.png
Moved the file 1264_IM-0179-2001.dcm.png
Moved the file 1265_IM-0179-2001.dcm.png
Moved the file 1266_IM-0179-2001.dcm.png
Moved the file 1267_IM-0179-1002.dcm.png
Moved the file 1268_IM-0180-2001.dcm.png
Moved the file 1268_IM-0180-3001.dcm.png
Moved the file 1269_IM-0181-2001.dcm.png
Moved the file 1270_IM-0181-2001.dcm.png
Moved the file 1271_IM-0182-2001.dcm.png
Moved the file 1272_IM-0183-1002.dcm.png
Moved the file 1273_IM-0183-2001.dcm.png
Moved the file 1274_IM-0183-2001.dcm.png
Moved the file 1275_IM-0184-2001.dcm.png
Moved the file 1276_IM-0184-2001.dcm.png
Moved the file 1277_IM-0185-2001.dcm.png
Moved the file 1278_IM-0185-1002.dcm.png
Moved the file 127_IM-0181-1002.dcm.png
Moved the file 1280_IM-0187-3001.dcm.png
Moved the file 1281_IM-0188-2001.dcm.png
Moved the file 1282_IM-0188-2001.dcm.png
Moved the file 1284_IM-0188-2001.dcm.png
Moved the file 1285_IM-0188-1001.dcm.png
Moved the file 1285_IM-0188-4001.dcm.png
Moved the file 1286_IM-0188-1002.dcm.png
Moved the file 1287_IM-0188-2001.dcm.png
Moved the file 1288_IM-0189-2001.dcm.png
Moved the file 1289_IM-0189-2001.dcm.png
Moved the file 128_IM-0186-82592002.dcm.png
Moved the file 1291_IM-0190-2001.dcm.png
Moved the file 1292_IM-0191-2001.dcm.png
Moved the file 1294_IM-0193-2001.dcm.png
Moved the file 1295_IM-0194-2002.dcm.png
Moved the file 1296_IM-0195-1001-0001.dcm.png
Moved the file 1297_IM-0195-1001.dcm.png
Moved the file 129_IM-0189-2001.dcm.png
Moved the file 12_IM-0133-2001.dcm.png
Moved the file 1300_IM-0198-2001.dcm.png
Moved the file 1301_IM-0198-2001.dcm.png
Moved the file 1302_IM-0198-2001.dcm.png
Moved the file 1303_IM-0199-2001-0002.dcm.png
Moved the file 1304_IM-0199-2001.dcm.png
Moved the file 1305_IM-0199-1002.dcm.png
Moved the file 1306_IM-0200-3001.dcm.png
Moved the file 1307_IM-0200-2001.dcm.png
Moved the file 1308_IM-0201-2001.dcm.png
Moved the file 1309_IM-0201-1001-0002.dcm.png
Moved the file 130_IM-0198-2001.dcm.png
Moved the file 1310_IM-0202-2001.dcm.png
Moved the file 1311_IM-0203-1002.dcm.png
Moved the file 1312_IM-0203-1002.dcm.png
Moved the file 1313_IM-0204-2001.dcm.png
Moved the file 1314_IM-0204-2001.dcm.png
Moved the file 1315_IM-0204-2001.dcm.png
Moved the file 1316_IM-0205-1003.dcm.png
Moved the file 1317_IM-0205-1002.dcm.png
Moved the file 1318_IM-0205-2001.dcm.png
Moved the file 1319_IM-0205-3001.dcm.png
Moved the file 131_IM-0202-2001.dcm.png
Moved the file 1320_IM-0207-2001.dcm.png
Moved the file 1321_IM-0207-2001.dcm.png
Moved the file 1323_IM-0209-2001.dcm.png
Moved the file 1324_IM-0209-2001.dcm.png
Moved the file 1326_IM-0210-0001-0001.dcm.png
Moved the file 1327_IM-0211-1002.dcm.png
Moved the file 1328_IM-0211-3001.dcm.png
Moved the file 1329_IM-0211-2001.dcm.png
Moved the file 1330_IM-0213-2001.dcm.png
Moved the file 1331_IM-0213-1002.dcm.png
Moved the file 1332_IM-0213-1001-0002.dcm.png
Moved the file 1333_IM-0214-2001.dcm.png
Moved the file 1334_IM-0214-2001.dcm.png
Moved the file 1335_IM-0215-1002.dcm.png
Moved the file 1336_IM-0216-2001.dcm.png
Moved the file 1337_IM-0216-3001.dcm.png
Moved the file 1338_IM-0217-1002.dcm.png
Moved the file 133_IM-0212-2001.dcm.png
Moved the file 133_IM-0212-3001.dcm.png
Moved the file 1340_IM-0220-2001.dcm.png
Moved the file 1341_IM-0220-2001.dcm.png
Moved the file 1342_IM-0221-2001.dcm.png
Moved the file 1343_IM-0222-0001-0001.dcm.png
Moved the file 1344_IM-0223-1002.dcm.png
Moved the file 1345_IM-0223-2001.dcm.png
Moved the file 1346_IM-0224-2001.dcm.png
Moved the file 1347_IM-0225-3001.dcm.png
Moved the file 1349_IM-0227-2001.dcm.png
Moved the file 1350_IM-0227-2001.dcm.png
Moved the file 1351_IM-0228-2001.dcm.png
Moved the file 1352_IM-0229-2001.dcm.png
Moved the file 1353_IM-0230-2001.dcm.png
Moved the file 1354_IM-0230-2001.dcm.png
Moved the file 1355_IM-0230-2001.dcm.png
Moved the file 1356_IM-0231-2001.dcm.png
Moved the file 1357_IM-0231-1002.dcm.png
Moved the file 1358_IM-0232-2001.dcm.png
Moved the file 1359_IM-0233-2001.dcm.png
Moved the file 135_IM-0227-3003.dcm.png
Moved the file 1360_IM-0234-0001-0002.dcm.png
Moved the file 1361_IM-0235-2001.dcm.png
Moved the file 1362_IM-0235-2001.dcm.png
Moved the file 1363_IM-0236-0001-0001.dcm.png
Moved the file 1364_IM-0237-2001.dcm.png
Moved the file 1365_IM-0237-2001.dcm.png
Moved the file 1366_IM-0237-2001.dcm.png
Moved the file 1367_IM-0237-2001.dcm.png
Moved the file 1368_IM-0237-2001.dcm.png
Moved the file 1369_IM-0238-2001.dcm.png
Moved the file 136_IM-0233-1002.dcm.png
Moved the file 1370_IM-0239-2001.dcm.png
Moved the file 1371_IM-0239-2001.dcm.png
Moved the file 1372_IM-0239-2001.dcm.png
Moved the file 1373_IM-0240-2001.dcm.png
Moved the file 1374_IM-0240-2001.dcm.png
Moved the file 1375_IM-0241-4001.dcm.png
Moved the file 1376_IM-0242-2001.dcm.png
Moved the file 1377_IM-0242-2001.dcm.png
Moved the file 1378_IM-0242-2001.dcm.png
Moved the file 1379_IM-0243-2001.dcm.png
Moved the file 137_IM-0238-2002.dcm.png
Moved the file 1380_IM-0245-1002.dcm.png
Moved the file 1381_IM-0245-2001.dcm.png
Moved the file 1382_IM-0245-2001.dcm.png
Moved the file 1383_IM-0245-1002.dcm.png
Moved the file 1384_IM-0246-2001.dcm.png
Moved the file 1385_IM-0246-2001.dcm.png
Moved the file 1386_IM-0246-2001.dcm.png
Moved the file 1387_IM-0246-2001.dcm.png
Moved the file 1388_IM-0246-2001.dcm.png
Moved the file 1389_IM-0247-2001.dcm.png
Moved the file 1389_IM-0247-3001.dcm.png
Moved the file 138_IM-0244-2001.dcm.png
Moved the file 1390_IM-0249-2001.dcm.png
Moved the file 1391_IM-0250-5001.dcm.png
Moved the file 1392_IM-0251-2001.dcm.png
Moved the file 1393_IM-0251-2001.dcm.png
Moved the file 1394_IM-0251-1002.dcm.png
Moved the file 1395_IM-0251-2001.dcm.png
Moved the file 1396_IM-0252-1001.dcm.png
Moved the file 1397_IM-0253-2001.dcm.png
Moved the file 1399_IM-0255-12012.dcm.png
Moved the file 139_IM-0248-3003.dcm.png
Moved the file 13_IM-0198-2001.dcm.png
Moved the file 1400_IM-0256-1002.dcm.png
Moved the file 1401_IM-0256-1002.dcm.png
Moved the file 1402_IM-0257-3001.dcm.png
Moved the file 1403_IM-0258-2001.dcm.png
Moved the file 1404_IM-0258-2001.dcm.png
Moved the file 1405_IM-0259-2001.dcm.png
Moved the file 1406_IM-0259-2001.dcm.png
Moved the file 1407_IM-0260-2001.dcm.png
Moved the file 1409_IM-0260-2001.dcm.png
Moved the file 1410_IM-0260-1002.dcm.png
Moved the file 1411_IM-0261-0001-0002.dcm.png
Moved the file 1412_IM-0262-3003.dcm.png
Moved the file 1413_IM-0263-1001.dcm.png
Moved the file 1414_IM-0264-1002.dcm.png
Moved the file 1415_IM-0264-2001.dcm.png
Moved the file 1416_IM-0265-2001.dcm.png
Moved the file 1417_IM-0266-1002.dcm.png
Moved the file 1418_IM-0267-1001.dcm.png
Moved the file 1419_IM-0267-2001.dcm.png
Moved the file 141_IM-0260-2001.dcm.png
Moved the file 1420_IM-0268-2001.dcm.png
Moved the file 1420_IM-0268-3001.dcm.png
Moved the file 1421_IM-0269-2001.dcm.png
Moved the file 1422_IM-0269-2001.dcm.png
Moved the file 1423_IM-0270-2001.dcm.png
Moved the file 1424_IM-0271-3003.dcm.png
Moved the file 1425_IM-0272-1002.dcm.png
Moved the file 1426_IM-0272-2001.dcm.png
Moved the file 1428_IM-0274-2001.dcm.png
Moved the file 1429_IM-0275-2001.dcm.png
Moved the file 142_IM-0267-2001.dcm.png
Moved the file 1431_IM-0278-2001.dcm.png
Moved the file 1432_IM-0278-2001.dcm.png
Moved the file 1433_IM-0278-2001.dcm.png
Moved the file 1434_IM-0279-2001.dcm.png
Moved the file 1435_IM-0280-2001.dcm.png
Moved the file 1436_IM-0280-1002.dcm.png
Moved the file 1437_IM-0281-2001.dcm.png
Moved the file 1438_IM-0282-1003.dcm.png
Moved the file 1439_IM-0282-1002.dcm.png
Moved the file 143_IM-0276-2001.dcm.png
Moved the file 1440_IM-0284-2001.dcm.png
Moved the file 1441_IM-0285-2001.dcm.png
Moved the file 1442_IM-0286-2001.dcm.png
Moved the file 1443_IM-0286-2001.dcm.png
Moved the file 1445_IM-0287-0001.dcm.png
Moved the file 1446_IM-0288-1002.dcm.png
Moved the file 1447_IM-0289-2001.dcm.png
Moved the file 1448_IM-0289-2001.dcm.png
Moved the file 1449_IM-0290-2001.dcm.png
Moved the file 1450_IM-0291-2001.dcm.png
Moved the file 1451_IM-0291-2001.dcm.png
Moved the file 1452_IM-0291-2001.dcm.png
Moved the file 1453_IM-0292-1001.dcm.png
Moved the file 1454_IM-0293-2001.dcm.png
Moved the file 1455_IM-0293-2001.dcm.png
Moved the file 1456_IM-0294-2001.dcm.png
Moved the file 1457_IM-0295-2002.dcm.png
Moved the file 1458_IM-0296-2001.dcm.png
Moved the file 1459_IM-0297-2001.dcm.png
Moved the file 145_IM-0290-2001.dcm.png
Moved the file 1460_IM-0298-2001.dcm.png
Moved the file 1461_IM-0299-2001.dcm.png
Moved the file 1462_IM-0299-2001.dcm.png
Moved the file 1464_IM-0301-2001.dcm.png
Moved the file 1465_IM-0302-2001.dcm.png
Moved the file 1466_IM-0302-1002.dcm.png
Moved the file 1467_IM-0302-2001.dcm.png
Moved the file 1468_IM-0303-2001.dcm.png
Moved the file 1469_IM-0303-2001.dcm.png
Moved the file 146_IM-0298-1001-0002.dcm.png
Moved the file 146_IM-0298-2001.dcm.png
Moved the file 1470_IM-0303-2001.dcm.png
Moved the file 1471_IM-0304-3001.dcm.png
Moved the file 1472_IM-0305-2001.dcm.png
Moved the file 1473_IM-0306-1002.dcm.png
Moved the file 1474_IM-0307-2001.dcm.png
Moved the file 1476_IM-0308-3001.dcm.png
Moved the file 1477_IM-0309-2001.dcm.png
Moved the file 1478_IM-0310-0001-0001.dcm.png
Moved the file 1479_IM-0311-2001.dcm.png
Moved the file 1480_IM-0311-2001.dcm.png
Moved the file 1481_IM-0312-2001.dcm.png
Moved the file 1483_IM-0313-2001.dcm.png
Moved the file 1484_IM-0313-2001.dcm.png
Moved the file 1485_IM-0313-2001.dcm.png
Moved the file 1487_IM-0314-2001.dcm.png

Removing lateral images

In [ ]:
shutil.rmtree(f'../chest-x-ray-data/processed_images/')